# Generated by Django 5.1.2 on 2024-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
